services:
  tomcat:
    build: build/dockerImage
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=75 -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError
      SPRING_PROFILES_ACTIVE:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    read_only: true
    tmpfs:
      - /tmp
    develop:
      watch:
        - action: rebuild
          path: build/libs/tomcat.jar
        - action: rebuild
          path: src/main/docker/Dockerfile
